image: webdriverio/selenium-standalone
   
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - echo $EMAIL
          - echo $PASS
          - npm install
          - npm run wdio