image: circleci/node:10.14-browsers
pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - npm ci
            - npm run wdio

  branches:
    master:
      - step:
          script:
            - npm ci
            - npm run wdio