image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - wdio config/wdio.smoke.js
        - step:
            name: Code linting
            script:
              - npm install eslint
              - wdio config/wdio.smoke.js
            caches:
              - node
