image: webdriverio/selenium-standalone
   
pipelines:
  custom:
    execute-autotests:
    - step:
        name: Test Execution
        script:
          - npm install
          - npm run wdio:sauce:web