pipelines:
  custom:
    customPipelineWithRunnerStep:
      - step:
          name: Install Repo
          runs-on: 
            - 'self.hosted'
            - 'macos'
          script:
            - npm install
            - npm run smoke