image: selenium/node-chrome
   
pipelines:
  custom:
    execute-autotests:
    - step:
        name: Test Execution
        script:
          - npm install
          - chromedriver
          - npm run smoke
