pipelines:
  default:
    - step:
       runs-on:
         - 'self.hosted'
         - 'macos'
       name: Install NPM
       script:
          - npm i
    - parallel:
        - step:
            name: Test Execution
            script:
              - wdio config/wdio.smoke.js