image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: Install
            caches:
              - node
            script:
              - npm install
        - step:
            name: Execute tests
            caches:
              - node
            script:
              - npm run smoke