image: node

pipelines:
  default:
    - step:
       name: Install NPM
       script:
          - npm i
    - parallel:
        - step:
            name: Test Execution
            script:
              - wdio config/wdio.smoke.js