image: webdriverio/selenium-standalone
   
pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm run wdio:sauce:web
          - npm run wdio:sauce:mobile