pipelines:
  custom:
    testRunner:
      - step:
          name: Install
          runs-on: 
            - 'macos'
          script:
            - npm install
            - npm run smoke
          caches:
            - node
definitions:
  caches:
    node: node