image: node

pipelines:
  default:
      - step:
          name: Login Tests Execution
          script:
            - npm install
            - wdio config/wdio.smoke.js --spec ./features/smoke/login/*.feature