pipelines:
  custom:
    testRunner:
      - step:
          name: Install
          runs-on: 
            - 'macos'
          script:
            - npm install
          caches:
            - node
      - step:
          name: Execute Tests
          script:
            - npm run smoke
definitions:
  caches:
    node: node