image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm run smoke
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npm run smoke
            caches:
              - node
